INSERT INTO TIPO_PREGUNTA VALUES(1,'abierta');
INSERT INTO TIPO_PREGUNTA VALUES(2,'unica');
INSERT INTO TIPO_PREGUNTA VALUES(3,'multiple');
INSERT INTO TIPO_PREGUNTA VALUES(4,'anioNac');

INSERT INTO PREGUNTA VALUES(1,2,'Sexo');
INSERT INTO PREGUNTA VALUES(2,4,'Año de Nacimiento');
INSERT INTO PREGUNTA VALUES(3,2,'Provincia');



INSERT INTO PROVINCIA VALUES(1,'San José');
INSERT INTO PROVINCIA VALUES(3,'Cartago');
INSERT INTO PROVINCIA VALUES(4,'Heredia');
INSERT INTO PROVINCIA VALUES(2,'Alajuela');
INSERT INTO PROVINCIA VALUES(5,'Guanacaste');
INSERT INTO PROVINCIA VALUES(6,'Puntarenas');
INSERT INTO PROVINCIA VALUES(7,'Limón');

INSERT INTO RESPUESTA VALUES(1,1,'Femenino');
INSERT INTO RESPUESTA VALUES(2,1,'Masculino');